### ISSUE TITLE
Unknown Filepath

### ISSUE THREAD

**Issue by OrangeKale64** [F-He/Discord_Bot_For_LGSM#5]
So I was trying to use this for my server, but it can't find the file path. I'm on windows 10. I don't have any clue why it doesn't work. Here is my config:

[general_settings]
bot_token = {I did put the token, it works fine}
bot_status = on Kalecraft MC
command_prefix = !

; Needs to be a Hex value.
bot_embed_color = #547e34

; Specify if and how many game servers can run at the same time.
allow_parallel_running = True
max_parallel_running_count = 4

[command_settings]
; Cooldown time in seconds between server commands.
start_server_cooldown = 5
stop_server_cooldown = 5

; Specify which role can execute a command.
; Can currently only be one role.
; The role name needs to be the exact same as in discord(including caps and spelling).
list = @everyone
status = @everyone
start = @everyone
stop = @everyone
update = @everyone
reloadConfig = @everyone

[game_servers]
; Specify here which game servers the bot should manage.
; For example a gmod server is registered like this:
; gmodserver = /home/gmodserver/gmodserver
; The value on the left represents the corresponding Linux User
; and the value on the right represents the path to the server file.
proxy = D:\Apps\Games\Minecraft Servers\servers\Waterfall\start.bat
hub = D:\Apps\Games\Minecraft Servers\servers\Hub\start.bat

[command_aliases]
; Split aliases with "," like this: help,info,?,serverinfo
help = info,?,hp
list = ls
status = stat,su
start = st
stop = sp
update = ud
reloadConfig = rc

[command_descriptions]
help = Shows all Commands.
start = Starts a Server. [`start <serverName>`]
stop = Stops a Server. [`stop <serverName>`]

**Comment by OrangeKale64** [comment]
Here is the bot console Traceback (most recent call last):
  File "C:\Users\{myname}\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\{myname}\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\{myname}\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by F-He** [comment]
This bot is designed to be used with [LinuxGSM ](https://linuxgsm.com/) on Linux.
Best wishes.

**Comment by OrangeKale64** [comment]
Could you make it work on windows somehow?
