### ISSUE TITLE
Error under starting. [Fixed]

### ISSUE THREAD

**Issue by MikkelDK** [F-He/Discord_Bot_For_LGSM#8]
Hi,

There is an error, under trying to starting the bot.

```
Task exception was never retrieved
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /usr/local/lib/python3.7/dist-packages/discord/client.py:545> exception=TypeError("__new__() got an unexpected keyword argument 'deny_new'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 547, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 511, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 433, in connect
    await self._connect()
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 397, in _connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.7/dist-packages/discord/gateway.py", line 470, in poll_event
    await self.received_message(msg)
  File "/usr/local/lib/python3.7/dist-packages/discord/gateway.py", line 424, in received_message
    func(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/state.py", line 664, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/state.py", line 639, in _get_create_guild
    guild._from_data(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/guild.py", line 246, in _from_data
    self._sync(guild)
  File "/usr/local/lib/python3.7/dist-packages/discord/guild.py", line 277, in _sync
    self._add_channel(CategoryChannel(guild=self, data=c, state=self._state))
  File "/usr/local/lib/python3.7/dist-packages/discord/channel.py", line 629, in __init__
    self._update(guild, data)
  File "/usr/local/lib/python3.7/dist-packages/discord/channel.py", line 640, in _update
    self._fill_overwrites(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

**What can I do here?**

**Comment by MikkelDK** [comment]
**Fixed with reinstalling discord.py**
`python3 -m pip install -U discord.py`
